# Generated by Django 4.0.4 on 2022-06-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('any_post', '0002_thefollowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='thefollowing',
            name='status',
            field=models.CharField(choices=[('a', 'accept'), ('p', 'pending')], default='p', max_length=1),
        ),
    ]
